name: "Retrieve JayTech Secret"
description: "Retrieves a single secret and exposes it as a plain output value."

inputs:
  jaytech-credential-key:
    description: "Credential Key used to authenticate"
    required: true
  secret:
    description: "Name of the JayTech-managed secret (e.g., MY_SECRET_ID)"
    required: true

outputs:
  secret-out:
    description: "Raw secret value (escaped for use in workflows)"
    value: ${{ steps.resolve.outputs.secret_out }}

runs:
  using: "composite"
  steps:
    - name: Fetch secret from Authorization Center
      id: resolve
      shell: bash
      run: |
        set -euo pipefail

        echo "🔐 Fetching secret '${{ inputs.secret }}'"

        RESPONSE=$(curl -s -w "%{http_code}" -o .secret-value.txt \
          -H "jaytech-credential-key: ${{ inputs.jaytech-credential-key }}" \
          "https://api.authorization-center.jaytech.nl/v3/secrets/${{ inputs.secret }}")

        if [[ "$RESPONSE" != "200" ]]; then
          echo "❌ Failed to fetch secret '${{ inputs.secret }}'. HTTP $RESPONSE"
          cat .secret-value.txt
          exit 1
        fi

        VALUE=$(cat .secret-value.txt | sed 's/"/\\"/g')

        echo "✅ Secret fetched. Setting output. "
        echo "secret_out=$VALUE" >> "$GITHUB_OUTPUT"
