name: .NET Build
description: Build a .NET solution. Action expect the repository to be prepared as a workflow-artifact (see https://github.com/JayTechNL/jaytech-tools-github-workflows/blob/master/README.md)
inputs:
  configuration:
    description: Select the configuration to run
    required: false
    default: Release
  solution-path:
    description: Specify the relative path to the .sln file
    required: false
    default: ""
  azure-api-key:
    description: Azure API key
    required: false
    default: ""
  azure-feed: 
    description: Azure feed
    required: false
    default: ""
  azure-source: 
    description: Azure source link in case private NuGet packages need to be fetched
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - if: inputs.azure-api-key != '' && inputs.azure-api-source != '' && inputs.azure-feed != ''
      name: Add Azure feed
      shell: bash
      run: dotnet nuget add source ${{ inputs.azure-feed }} --name ${{inputs.azure-source}} --username az --password ${{ inputs.azure-api-key }} --store-password-in-clear-text      
    - name: .NET Build
      shell: bash
      run: dotnet build workflow/repository/${{inputs.solution-path}} --configuration ${{inputs.configuration}}