name: "quasar-build-android"
description: Build android contents for Quasar
inputs:
  folder:
    description: Folder to use the build command in
    required: false
    default: "./workflow/repository"
runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Quasar Build Android
      working-directory: ${{inputs.folder}}
      run: |
        npm install
        npm i -g @quasar/cli
        npm install -g cordova
        quasar build -m cordova -T android --release
      shell: bash
    - name: Upload quasar-android contents
      uses: actions/upload-artifact@v1
      with:
        name: quasar-build-android
        path: ${{inputs.folder}}/dist/cordova
        retention-days: 30
