name: "quasar-build-android"
description: Android contents for Quasar
inputs:
  folder:
    description: "Folder to use the build command in"
    required: false
    default: "./workflow/repository"
runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v2  # Updated to v2
      with:
        node-version: "16"
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Changed to Temurin as Adopt is now part of the Eclipse Foundation
        
    - name: Quasar Build for Android
      working-directory: ${{inputs.folder}}
      shell: bash
      run: |
        npm install --unsafe-perm=true --allow-root
        npm install -g @quasar/cli
        npm install -g cordova
        # Removed update-alternatives commands as setup-java action correctly configures JDK
        npx quasar build -m cordova -T android --release
